project:
  type: website
  output-dir: docs
  
website:
  favicon: "/images/wdbrain.png"
  title: "Will Decker"
  page-footer: 
    left: "2023 Â©ï¸ Will Decker - [GNU General Public License v3.0](LICENSE)"
  sidebar:
    logo: "/images/wdbrain.png"
    style: "docked"
    background-color: "#DCDCDC"
    search: true
    contents:
      - text: "Home ğŸ "
        file: index.qmd
      - text: "About me ğŸ‘¤"
        file: about.qmd
      - text: "CV ğŸ“„"
        file: cv.qmd
      - text: "Open Science ğŸ“¤ ğŸ§ª"
        file: opensci.qmd
      - text: "My Open Science ğŸ‘¤ ğŸ§ª"
        file: mysci.qmd
      - section: "Projects ğŸ§¬"
        contents: 
          - currentprojects.qmd
          - archive.qmd

            
format: 
  html:
    theme: darkly
    css: styles.css
    toc: true